#---------------------------------------------------
#General Parameters 
#---------------------------------------------------
ALL: "ZebrafishesNature"
SAMPLES: "samples_nature.tsv"
ANNOFILE: "annotationsi_nature.txt"

